import { defaultFontPresetKey } from '../../../shared/font-presets';
import type { ThemePresetSeed } from '../types/theme';

export const themePresetSeeds: ThemePresetSeed[] = [
    {
        key: 'couples-glow',
        name: 'Couples Glow',
        audience: 'couples',
        description: 'Romantic and polished for shared goals, rituals, and rewards.',
        tokens: {
            background: '#fff1f4',
            foreground: '#3b1022',
            card: '#fff8fb',
            cardForeground: '#3b1022',
            primary: '#d81b60',
            primaryForeground: '#fff7fb',
            secondary: '#ffc7da',
            secondaryForeground: '#6d1d41',
            accent: '#ff7aa8',
            accentForeground: '#4c1027',
            muted: '#ffe2ec',
            mutedForeground: '#8a4964',
            border: '#f3b4cb',
            ring: '#d81b60',
            heroFrom: '#ffdbe8',
            heroVia: '#ffbfd5',
            heroTo: '#ff9fbb',
            surface: '#fff1f4',
            surfaceAlt: '#ffe5ee',
            fontSans: '"Nunito", sans-serif',
            fontDisplay: '"Pixelify Sans", cursive',
        },
    },
    {
        key: 'kids-spark',
        name: 'Kids Spark',
        audience: 'boys-girls-kids',
        description: 'Playful and bright for family challenges, chores, and adventure streaks.',
        tokens: {
            background: '#f4fbff',
            foreground: '#15324a',
            card: '#ffffff',
            cardForeground: '#15324a',
            primary: '#2f6fff',
            primaryForeground: '#f8fbff',
            secondary: '#cfe7ff',
            secondaryForeground: '#204874',
            accent: '#ffca3a',
            accentForeground: '#513400',
            muted: '#e8f4ff',
            mutedForeground: '#597998',
            border: '#bdd8fb',
            ring: '#2f6fff',
            heroFrom: '#dff2ff',
            heroVia: '#bfe4ff',
            heroTo: '#ffe68f',
            surface: '#f4fbff',
            surfaceAlt: '#eaf6ff',
            fontSans: '"Nunito", sans-serif',
            fontDisplay: '"Pixelify Sans", cursive',
        },
    },
    {
        key: 'friends-arcade',
        name: 'Friends Arcade',
        audience: 'friends',
        description: 'Competitive and energetic for squads, roommates, and challenge circles.',
        tokens: {
            background: '#f4f7fb',
            foreground: '#172433',
            card: '#ffffff',
            cardForeground: '#172433',
            primary: '#0c8f7a',
            primaryForeground: '#f2fffc',
            secondary: '#d3f4ed',
            secondaryForeground: '#134c44',
            accent: '#ff8b42',
            accentForeground: '#472109',
            muted: '#eaf1f6',
            mutedForeground: '#617280',
            border: '#d6e1ea',
            ring: '#0c8f7a',
            heroFrom: '#e0fff5',
            heroVia: '#cde8ff',
            heroTo: '#ffd2b8',
            surface: '#f4f7fb',
            surfaceAlt: '#ebf1f6',
            fontSans: '"Nunito", sans-serif',
            fontDisplay: '"Pixelify Sans", cursive',
        },
    },
    {
        key: 'family-camp',
        name: 'Family Camp',
        audience: 'family',
        description: 'Warm and grounded for households, routines, and shared milestones.',
        tokens: {
            background: '#fbf7ec',
            foreground: '#2f2a21',
            card: '#fffdf7',
            cardForeground: '#2f2a21',
            primary: '#8a6a36',
            primaryForeground: '#fffef8',
            secondary: '#eadfbf',
            secondaryForeground: '#544424',
            accent: '#cf7a3b',
            accentForeground: '#371807',
            muted: '#f2ebd8',
            mutedForeground: '#6f6654',
            border: '#ddd0ad',
            ring: '#8a6a36',
            heroFrom: '#f8efcf',
            heroVia: '#f7d8b8',
            heroTo: '#dfe8c9',
            surface: '#fbf7ec',
            surfaceAlt: '#f4eddc',
            fontSans: '"Nunito", sans-serif',
            fontDisplay: '"Pixelify Sans", cursive',
        },
    },
    {
        key: 'bubble-blast',
        name: 'Bubble Blast',
        audience: 'friends',
        description: 'Sugary, playful, and loud for chaotic score races and bright streaks.',
        tokens: {
            background: '#fff8ff',
            foreground: '#36173d',
            card: '#ffffff',
            cardForeground: '#36173d',
            primary: '#ff4fa3',
            primaryForeground: '#fff8fd',
            secondary: '#ffd5ef',
            secondaryForeground: '#6a2353',
            accent: '#53d8fb',
            accentForeground: '#113d4c',
            muted: '#ffe8f7',
            mutedForeground: '#865777',
            border: '#f4bfdc',
            ring: '#ff4fa3',
            heroFrom: '#ffd7f7',
            heroVia: '#ffc4df',
            heroTo: '#b8f2ff',
            surface: '#fff8ff',
            surfaceAlt: '#fff0fa',
            fontSans: '"Helvetica Neue", "Arial", sans-serif',
            fontDisplay: '"Arial Black", "Impact", sans-serif',
        },
    },
    {
        key: 'glitch-carnival',
        name: 'Glitch Carnival',
        audience: 'friends',
        description: 'Offbeat carnival neon with sharp contrast and a noisy arcade edge.',
        tokens: {
            background: '#f7f4ff',
            foreground: '#23183d',
            card: '#ffffff',
            cardForeground: '#23183d',
            primary: '#6f2cff',
            primaryForeground: '#f8f5ff',
            secondary: '#e4d8ff',
            secondaryForeground: '#3f2571',
            accent: '#ffb703',
            accentForeground: '#4e3200',
            muted: '#eee7ff',
            mutedForeground: '#70658d',
            border: '#d7cbfb',
            ring: '#6f2cff',
            heroFrom: '#e4dcff',
            heroVia: '#d0c0ff',
            heroTo: '#ffd27f',
            surface: '#f7f4ff',
            surfaceAlt: '#ede7fb',
            fontSans: '"Trebuchet MS", "Verdana", sans-serif',
            fontDisplay: '"Courier New", "Lucida Console", monospace',
        },
    },
    {
        key: 'gummy-grid',
        name: 'Gummy Grid',
        audience: 'family',
        description: 'Soft candy colors and friendly contrast for playful households and kid squads.',
        tokens: {
            background: '#fffdf4',
            foreground: '#3f2f1e',
            card: '#ffffff',
            cardForeground: '#3f2f1e',
            primary: '#ff7f50',
            primaryForeground: '#fffaf6',
            secondary: '#ffe0bf',
            secondaryForeground: '#6d4a1f',
            accent: '#7ad66d',
            accentForeground: '#1f4b19',
            muted: '#fff1d8',
            mutedForeground: '#8c7054',
            border: '#f1d3b0',
            ring: '#ff7f50',
            heroFrom: '#ffecc7',
            heroVia: '#ffd4c5',
            heroTo: '#d8ffd4',
            surface: '#fffdf4',
            surfaceAlt: '#fff4df',
            fontSans: '"Nunito", sans-serif',
            fontDisplay: '"Pixelify Sans", cursive',
        },
    },
    {
        key: 'midnight-laser',
        name: 'Midnight Laser',
        audience: 'friends',
        description: 'Dark arcade laser beams with crisp type for competitive late-night energy.',
        tokens: {
            background: '#0f1127',
            foreground: '#f5f7ff',
            card: '#181b3a',
            cardForeground: '#f5f7ff',
            primary: '#00e5ff',
            primaryForeground: '#09111f',
            secondary: '#253060',
            secondaryForeground: '#dce8ff',
            accent: '#ff4d9d',
            accentForeground: '#fff1f7',
            muted: '#1b2148',
            mutedForeground: '#aab6df',
            border: '#2c3568',
            ring: '#00e5ff',
            heroFrom: '#141936',
            heroVia: '#1f2b5c',
            heroTo: '#3c1450',
            surface: '#0f1127',
            surfaceAlt: '#171b39',
            fontSans: '"Trebuchet MS", "Verdana", sans-serif',
            fontDisplay: '"Courier New", "Lucida Console", monospace',
        },
    },
    {
        key: 'sunset-synth',
        name: 'Sunset Synth',
        audience: 'couples',
        description: 'Stylish sunset gradients with a lounge feel for glamorous scoreboards and soft neon.',
        tokens: {
            background: '#fff6ef',
            foreground: '#3a1f2f',
            card: '#fffdf9',
            cardForeground: '#3a1f2f',
            primary: '#ff6b6b',
            primaryForeground: '#fff8f6',
            secondary: '#ffd8c7',
            secondaryForeground: '#6f3f31',
            accent: '#8f7cff',
            accentForeground: '#20174f',
            muted: '#ffe9dc',
            mutedForeground: '#916b70',
            border: '#f3c8b7',
            ring: '#ff6b6b',
            heroFrom: '#ffd6c2',
            heroVia: '#ffb3c8',
            heroTo: '#c9c0ff',
            surface: '#fff6ef',
            surfaceAlt: '#ffede3',
            fontSans: '"Gill Sans", "Trebuchet MS", sans-serif',
            fontDisplay: '"Georgia", "Times New Roman", serif',
        },
    },
];

export const defaultThemeKey = themePresetSeeds[0].key;

export const defaultContent = {
    fontPresetKey: defaultFontPresetKey,
    loginTitle: 'Welcome back to your shared adventure.',
    loginMessage: 'Sign in to manage goals, complete quests, and unlock rewards together.',
    loginImageUrl: null,
    loginBackgroundImageUrl: null,
    loginBackgroundImageSource: null,
    loginBackgroundImageAsset: null,
    loginBackgroundVideoUrl: null,
    loginBackgroundVideoSource: null,
    loginBackgroundVideoAsset: null,
    dashboardTitle: 'Today’s momentum starts here.',
    dashboardMessage: 'Turn everyday routines into a game your group actually wants to keep playing.',
    onboardingIntroEyebrow: 'Insert coin to begin',
    onboardingIntroTitle: 'Boot your own home arcade.',
    onboardingIntroMessage: 'Tune the look, mint your first players, and wire up the first quests before the cabinet opens to everyone else.',
    onboardingLaunchTitle: 'Ready to press start?',
    onboardingLaunchMessage: 'Run one final systems check, launch the realm, and open the cabinet to your players.',
};
